markdown: kramdown
highlighter: rouge
# having a host parameter like this allows us to debug
# the application in the local network
host: 0.0.0.0
exclude:
  [
    package.json,
    jekyll-build.sh,
    generate.sh,
    README.md,
    bower_components,
    node_modules,
    gestalt,
    playground,
    build-tmp,
    excludes,
  ]
sass:
  sass_dir: assets/_scss
  style: compressed
baseurl: ''
kramdown:
  input: GFM
  syntax_highlighter: rouge
  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  # syntax_highlighter_opts:
  #   # Rouge Options › https://github.com/jneen/rouge#full-options
  #   css_class: 'highlight'
  #   span:
  #     line_numbers: false
  #   block:
  #     line_numbers: true
  #     start_line: 1
excerpt_separator: '<!-- more -->'
repo_url: https://github.com/ff6347/gestalten-in-code
source_url: https://github.com/ff6347/gestalten-in-code/tree/master
